export enum ErrorCode {
  API_NOT_FOUND_USER_BY_EMAIL_OR_PHONE = 'API_NOT_FOUND_USER_BY_EMAIL_OR_PHONE',
  API_NULL_USER = 'API_NULL_USER',
  API_DUPLICATE_EMAIL = 'API_DUPLICATE_EMAIL',
  API_TOKEN_INVALID = 'API_TOKEN_INVALID',
  API_BAD_CREDENTIAL = 'API_BAD_CREDENTIAL',
  API_ACCESS_NOT_ALLOWED = 'API_ACCESS_NOT_ALLOWED',
  API_UNVERIFIED_USER = 'API_UNVERIFIED_USER',
}

export enum PluralErrorCode {}
